<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\OrganizeApp\OrganizeApp.Client\Pages\Authorization\RedirectToLogin.razor" Link="RedirectToLogin.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.22" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="8.0.22" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrganizeApp.Domain\OrganizeApp.Domain.csproj" />
    <ProjectReference Include="..\OrganizeApp.Shared\OrganizeApp.Shared.csproj" />
  </ItemGroup>

</Project>
